add_subdirectory(data) # this is corsika-data (submodule)
add_subdirectory(common)
add_subdirectory(pythia8)
add_subdirectory(sibyll)
add_subdirectory(sophia)
add_subdirectory(qgsjetII)
add_subdirectory(qgsjetIII)
add_subdirectory(urqmd)
add_subdirectory(epos-lhcr)
add_subdirectory(epos-lhc)
add_subdirectory(tauola)
add_subdirectory(fluka)
add_subdirectory(conex) # temporarily disabled
