# find_package(PROPOSAL REQUIRED ${LIB_INCLUDE})


FILE (GLOB MODEL_SOURCES *.cc)
FILE (GLOB MODEL_HEADERS *.h)
SET (MODEL_NAMESPACE corsika/process/proposal)

ADD_LIBRARY (ProcessProposal STATIC ${MODEL_SOURCES})
CORSIKA_COPY_HEADERS_TO_NAMESPACE (ProcessProposal ${MODEL_NAMESPACE} ${MODEL_HEADERS})

SET_TARGET_PROPERTIES ( ProcessProposal PROPERTIES VERSION ${PROJECT_VERSION}
    SOVERSION 1
    #  PUBLIC_HEADER "${MODEL_HEADERS}"
  )

TARGET_LINK_LIBRARIES (
  ProcessProposal
  CORSIKAenvironment
  ${PROPOSAL_LIBRARY}
  )

TARGET_INCLUDE_DIRECTORIES (
  ProcessProposal
  INTERFACE
  $<BUILD_INTERFACE:${PROJECT_BINARY_DIR}/include>
  $<INSTALL_INTERFACE:include/include>
  )

TARGET_INCLUDE_DIRECTORIES (
  ProcessProposal
  SYSTEM
  PUBLIC ${PROPOSAL_INCLUDE_DIR}
  INTERFACE ${PROPOSAL_INCLUDE_DIR}
  )

INSTALL (
  TARGETS ProcessProposal
  LIBRARY DESTINATION lib
  ARCHIVE DESTINATION lib
#  PUBLIC_HEADER DESTINATION include/${MODEL_NAMESPACE}
  )
